// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Admin        string
	Domain       string
	DomainAdmins string
	Mailbox      string
}{
	Admin:        "admin",
	Domain:       "domain",
	DomainAdmins: "domain_admins",
	Mailbox:      "mailbox",
}
