// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDomains(t *testing.T) {
	t.Parallel()

	query := Domains()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDomainsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDomainsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Domains().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDomainsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DomainSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDomainsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DomainExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Domain exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DomainExists to return true, but got false.")
	}
}

func testDomainsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	domainFound, err := FindDomain(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if domainFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDomainsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Domains().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDomainsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Domains().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDomainsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	domainOne := &Domain{}
	domainTwo := &Domain{}
	if err = randomize.Struct(seed, domainOne, domainDBTypes, false, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}
	if err = randomize.Struct(seed, domainTwo, domainDBTypes, false, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = domainOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = domainTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Domains().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDomainsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	domainOne := &Domain{}
	domainTwo := &Domain{}
	if err = randomize.Struct(seed, domainOne, domainDBTypes, false, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}
	if err = randomize.Struct(seed, domainTwo, domainDBTypes, false, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = domainOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = domainTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func domainBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func domainAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Domain) error {
	*o = Domain{}
	return nil
}

func testDomainsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Domain{}
	o := &Domain{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, domainDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Domain object: %s", err)
	}

	AddDomainHook(boil.BeforeInsertHook, domainBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	domainBeforeInsertHooks = []DomainHook{}

	AddDomainHook(boil.AfterInsertHook, domainAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	domainAfterInsertHooks = []DomainHook{}

	AddDomainHook(boil.AfterSelectHook, domainAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	domainAfterSelectHooks = []DomainHook{}

	AddDomainHook(boil.BeforeUpdateHook, domainBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	domainBeforeUpdateHooks = []DomainHook{}

	AddDomainHook(boil.AfterUpdateHook, domainAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	domainAfterUpdateHooks = []DomainHook{}

	AddDomainHook(boil.BeforeDeleteHook, domainBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	domainBeforeDeleteHooks = []DomainHook{}

	AddDomainHook(boil.AfterDeleteHook, domainAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	domainAfterDeleteHooks = []DomainHook{}

	AddDomainHook(boil.BeforeUpsertHook, domainBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	domainBeforeUpsertHooks = []DomainHook{}

	AddDomainHook(boil.AfterUpsertHook, domainAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	domainAfterUpsertHooks = []DomainHook{}
}

func testDomainsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDomainsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(domainColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDomainToManyAdmins(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c Admin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, adminDBTypes, false, adminColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, adminDBTypes, false, adminColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into `domain_admins` (`Domain_id`, `Admin_id`) values (?, ?)", a.ID, b.ID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into `domain_admins` (`Domain_id`, `Admin_id`) values (?, ?)", a.ID, c.ID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.Admins().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ID == b.ID {
			bFound = true
		}
		if v.ID == c.ID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := DomainSlice{&a}
	if err = a.L.LoadAdmins(ctx, tx, false, (*[]*Domain)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Admins); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Admins = nil
	if err = a.L.LoadAdmins(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Admins); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testDomainToManyDomainMailboxes(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c Mailbox

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, mailboxDBTypes, false, mailboxColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, mailboxDBTypes, false, mailboxColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.DomainID, a.ID)
	queries.Assign(&c.DomainID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.DomainMailboxes().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.DomainID, b.DomainID) {
			bFound = true
		}
		if queries.Equal(v.DomainID, c.DomainID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := DomainSlice{&a}
	if err = a.L.LoadDomainMailboxes(ctx, tx, false, (*[]*Domain)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DomainMailboxes); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.DomainMailboxes = nil
	if err = a.L.LoadDomainMailboxes(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.DomainMailboxes); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testDomainToManyAddOpAdmins(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c, d, e Admin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, false, strmangle.SetComplement(domainPrimaryKeyColumns, domainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Admin{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, adminDBTypes, false, strmangle.SetComplement(adminPrimaryKeyColumns, adminColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Admin{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddAdmins(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.Domains[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.Domains[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.Admins[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Admins[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Admins().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testDomainToManySetOpAdmins(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c, d, e Admin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, false, strmangle.SetComplement(domainPrimaryKeyColumns, domainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Admin{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, adminDBTypes, false, strmangle.SetComplement(adminPrimaryKeyColumns, adminColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetAdmins(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Admins().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetAdmins(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Admins().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.Domains) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.Domains) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.Domains[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.Domains[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.Admins[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Admins[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testDomainToManyRemoveOpAdmins(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c, d, e Admin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, false, strmangle.SetComplement(domainPrimaryKeyColumns, domainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Admin{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, adminDBTypes, false, strmangle.SetComplement(adminPrimaryKeyColumns, adminColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddAdmins(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Admins().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveAdmins(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Admins().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.Domains) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.Domains) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.Domains[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Domains[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.Admins) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Admins[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Admins[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testDomainToManyAddOpDomainMailboxes(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c, d, e Mailbox

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, false, strmangle.SetComplement(domainPrimaryKeyColumns, domainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Mailbox{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, mailboxDBTypes, false, strmangle.SetComplement(mailboxPrimaryKeyColumns, mailboxColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Mailbox{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddDomainMailboxes(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.DomainID) {
			t.Error("foreign key was wrong value", a.ID, first.DomainID)
		}
		if !queries.Equal(a.ID, second.DomainID) {
			t.Error("foreign key was wrong value", a.ID, second.DomainID)
		}

		if first.R.Domain != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Domain != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.DomainMailboxes[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.DomainMailboxes[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.DomainMailboxes().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testDomainToManySetOpDomainMailboxes(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c, d, e Mailbox

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, false, strmangle.SetComplement(domainPrimaryKeyColumns, domainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Mailbox{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, mailboxDBTypes, false, strmangle.SetComplement(mailboxPrimaryKeyColumns, mailboxColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetDomainMailboxes(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.DomainMailboxes().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetDomainMailboxes(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.DomainMailboxes().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DomainID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DomainID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.DomainID) {
		t.Error("foreign key was wrong value", a.ID, d.DomainID)
	}
	if !queries.Equal(a.ID, e.DomainID) {
		t.Error("foreign key was wrong value", a.ID, e.DomainID)
	}

	if b.R.Domain != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Domain != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Domain != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Domain != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.DomainMailboxes[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.DomainMailboxes[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testDomainToManyRemoveOpDomainMailboxes(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Domain
	var b, c, d, e Mailbox

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, domainDBTypes, false, strmangle.SetComplement(domainPrimaryKeyColumns, domainColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Mailbox{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, mailboxDBTypes, false, strmangle.SetComplement(mailboxPrimaryKeyColumns, mailboxColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddDomainMailboxes(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.DomainMailboxes().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveDomainMailboxes(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.DomainMailboxes().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.DomainID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.DomainID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Domain != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Domain != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Domain != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Domain != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.DomainMailboxes) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.DomainMailboxes[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.DomainMailboxes[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testDomainsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDomainsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DomainSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDomainsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Domains().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	domainDBTypes = map[string]string{`ID`: `bigint`, `Domain`: `varchar`, `Description`: `varchar`, `MaxAliases`: `int`, `AliasCount`: `bigint`, `MaxMailboxes`: `int`, `MailboxCount`: `bigint`, `MaxQuota`: `bigint`, `Quota`: `bigint`, `Transport`: `varchar`, `Backupmx`: `tinyint`, `Active`: `tinyint`, `Homedir`: `varchar`, `Maildir`: `varchar`, `UID`: `int`, `Gid`: `int`, `Created`: `datetime`, `Modified`: `datetime`}
	_             = bytes.MinRead
)

func testDomainsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(domainPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(domainAllColumns) == len(domainPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, domainDBTypes, true, domainPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDomainsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(domainAllColumns) == len(domainPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Domain{}
	if err = randomize.Struct(seed, o, domainDBTypes, true, domainColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, domainDBTypes, true, domainPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(domainAllColumns, domainPrimaryKeyColumns) {
		fields = domainAllColumns
	} else {
		fields = strmangle.SetComplement(
			domainAllColumns,
			domainPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DomainSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDomainsUpsert(t *testing.T) {
	t.Parallel()

	if len(domainAllColumns) == len(domainPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLDomainUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Domain{}
	if err = randomize.Struct(seed, &o, domainDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Domain: %s", err)
	}

	count, err := Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, domainDBTypes, false, domainPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Domain struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Domain: %s", err)
	}

	count, err = Domains().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
